version: '3.8'

services:
  app:
    build: ./
    command: ./wait-for-postgres.sh db ./todolist
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SSL_MODE=${SSL_MODE}

  db:
    restart: always
    image: postgres
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

